In [71]:
import numpy as np
import pandas as pd
import shlex

from __future__ import print_function, division
from future.utils import iteritems
from builtins import range
#we use gensim so we can read the bin file who has the vocabulary
from gensim.models import KeyedVectors

import sys
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier

import seaborn as sns

In [72]:
data = pd.read_csv('data.csv')
dataframe=pd.DataFrame(data)
dataframe

,linkedinProfile,Description,location,fullName,company,jobTitle,jobDuration,company2,jobTitle2,jobDuration2,skill1,skill2,skill3,skill4,skill5,jobLocation,jobLocation2
0,https://www.linkedin.com/in/mondher-menaa-5934...,Full-Stack developer,"Tunis, Tunisia",Mondher Menaa,NearTeam,Full-stack Developer,Jan 2020 - Present · 2 yrs 3 mos,Talan Tunisie,Software Engineer,Aug 2019 - Sep 2019 · 2 mos,Java,Angular,Scrum,J2EE,.NET,"Tunis, Tunisie","Tunis, Tunisia"
1,https://www.linkedin.com/in/dorra-dalhoumi/?or...,"Data Analyst, BI Consultant",France,Dorra Dalhoumi,Streamlink,Business Intelligence Consultant,Jan 2022 - Present · 3 mos,Groupe Magasin Général,Ingénieur BI,Jan 2021 - Jan 2022 · 1 yr 1 mo,Power BI,Big Data,Scrum,BI,GIT,France,"Tunis, Tunisie"
2,https://www.linkedin.com/in/abdouli-adem-47569...,Data Engineering Intern at Fusionbase,Germany,Abdouli Adem,Fusionbase,Data Engineering Intern,Oct 2020 - Present · 1 yr 6 mos,MS Solutions,Junior Data analyst,Jul 2019 - Aug 2019 · 2 mos,SQL,Java,Javascript,Python,C,Germany,"Tunis, Tunisie"
3,https://www.linkedin.com/in/chahnez-kasraoui-0...,Consultant BI,"Tunis, Tunisia",Chahnez KASRAOUI,EY,Consultant BI,Jul 2021 - Present · 9 mos,VERMEG,Stage PFE,Feb 2020 - Oct 2020 · 9 mos,analyses des données,Microsoft SQL Server,c++,\nHTML,Microsoft Office,"Tunis, Tunisie","Tunis, Tunisie"
4,https://www.linkedin.com/in/alaedine-omri/?ori...,Software engineer,"Tunis, Tunisia",Alaedine Omri,Epilert,Web Developer,Feb 2020 - Dec 2020 · 11 mos,Delta Motors,Web Developer,Jul 2019 - Sep 2019 · 3 mos,Python,HTML,MySQL,CSS,Laravel,"Tunis, Tunisie","Tunis, Tunisie"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,https://www.linkedin.com/in/omarmansr/,Business Intelligence Developer,"Berlin, Berlin, Allemagne",Omar Mansour,koawach,Business Intelligence Developer,nov. 2017 - aujourd’hui · 4 ans 4 mois,koawach,Business Intelligence Intern,avr. 2017 - nov. 2017 · 8 mois,Data Mining,SharePoint,Analyses Big Data,ASP.NET,SSIS,NaN,NaN
994,https://www.linkedin.com/in/malek-bejaoui/,Lead Consultant | Java Engineer | Software Arc...,"Düsseldorf, Rhénanie du Nord-Westphalie, Allem...",Malek Bejaoui,CGI,Lead Consultant,sept. 2020 - aujourd’hui · 1 an 6 mois,rising systems,DevOps Engineer,nov. 2019 - sept. 2020 · 11 mois,Java,Amazon Web Services (AWS),SQL,Web Design,Graphic Design,"Düsseldorf, North Rhine-Westphalia, Germany",NaN
995,https://www.linkedin.com/in/ahmeddrira/,Senior Software Engineer (VR/AR/XR) at ZREALIT...,"Mannheim, Bade-Wurtemberg, Allemagne",Ahmed Drira,ZREALITY GmbH,Senior Software Engineer,déc. 2018 - aujourd’hui · 3 ans 3 mois,ZREALITY GmbH,Software Engineer,avr. 2017 - aujourd’hui · 4 ans 11 mois,Java,C#,Android Development,iOS Development,Android,"Kaiserslautern, Rhineland-Palatinate, Germany","Kaiserslautern, Germany"
996,https://www.linkedin.com/in/ahmed-khalil-bejao...,Senior Software Engineer at Finway GmbH,"Munich, Bavière, Allemagne",Ahmed Khalil Bejaoui,finway,Senior Full Stack Engineer,mars 2020 - aujourd’hui · 2 ans,Holiday Extras GmbH,Software Engineer,nov. 2019 - mars 2020 · 5 mois,SQL,HTML,Web Development,Business Analysis,Program Management,"Munich, Bavaria, Germany","Munich Area, Germany"
997,https://www.linkedin.com/in/wejdene-benjeddou-...,Data Science engineering student looking for a...,"Giessen, Hesse, Allemagne",Wejdene Benjeddou,BFPME - Banque de Financement des Petites & Mo...,Data Analyst & scientist,juin 2021 · 1 mois,NaN,NaN,NaN,Analytical Skills,Mathematics,Python (Programming Language),Data Analysis,Oracle Database,Tunisia,NaN

In [73]:
dataframe.isnull().sum()

linkedinProfile      2
Description          2
location             2
fullName             2
company             12
jobTitle            12
jobDuration         14
company2            35
jobTitle2           35
jobDuration2        35
skill1              20
skill2              20
skill3              20
skill4              20
skill5              22
jobLocation        401
jobLocation2       447
dtype: int64

In [74]:
dataframe.fillna({'location':'Tunis, Tunisia','jobLocation':'Tunis, Tunisia','jobLocation2':'unis, Tunisia'}, inplace=True)
dataframe.fillna({'company':'CGI','company2':'EY'}, inplace=True)
dataframe.fillna({'skill1':'Java','skill2':'Angular','skill3':'SQL','skill4':'HTML','skill5':'CSS'}, inplace=True)
#replacing missing values in location ,company and skillls attributes by the most frequent values

In [75]:
dataframe.isnull().sum()

linkedinProfile     2
Description         2
location            0
fullName            2
company             0
jobTitle           12
jobDuration        14
company2            0
jobTitle2          35
jobDuration2       35
skill1              0
skill2              0
skill3              0
skill4              0
skill5              0
jobLocation         0
jobLocation2        0
dtype: int64

In [76]:
dataframe.dropna(inplace=True)

In [77]:
dataframe

,linkedinProfile,Description,location,fullName,company,jobTitle,jobDuration,company2,jobTitle2,jobDuration2,skill1,skill2,skill3,skill4,skill5,jobLocation,jobLocation2
0,https://www.linkedin.com/in/mondher-menaa-5934...,Full-Stack developer,"Tunis, Tunisia",Mondher Menaa,NearTeam,Full-stack Developer,Jan 2020 - Present · 2 yrs 3 mos,Talan Tunisie,Software Engineer,Aug 2019 - Sep 2019 · 2 mos,Java,Angular,Scrum,J2EE,.NET,"Tunis, Tunisie","Tunis, Tunisia"
1,https://www.linkedin.com/in/dorra-dalhoumi/?or...,"Data Analyst, BI Consultant",France,Dorra Dalhoumi,Streamlink,Business Intelligence Consultant,Jan 2022 - Present · 3 mos,Groupe Magasin Général,Ingénieur BI,Jan 2021 - Jan 2022 · 1 yr 1 mo,Power BI,Big Data,Scrum,BI,GIT,France,"Tunis, Tunisie"
2,https://www.linkedin.com/in/abdouli-adem-47569...,Data Engineering Intern at Fusionbase,Germany,Abdouli Adem,Fusionbase,Data Engineering Intern,Oct 2020 - Present · 1 yr 6 mos,MS Solutions,Junior Data analyst,Jul 2019 - Aug 2019 · 2 mos,SQL,Java,Javascript,Python,C,Germany,"Tunis, Tunisie"
3,https://www.linkedin.com/in/chahnez-kasraoui-0...,Consultant BI,"Tunis, Tunisia",Chahnez KASRAOUI,EY,Consultant BI,Jul 2021 - Present · 9 mos,VERMEG,Stage PFE,Feb 2020 - Oct 2020 · 9 mos,analyses des données,Microsoft SQL Server,c++,\nHTML,Microsoft Office,"Tunis, Tunisie","Tunis, Tunisie"
4,https://www.linkedin.com/in/alaedine-omri/?ori...,Software engineer,"Tunis, Tunisia",Alaedine Omri,Epilert,Web Developer,Feb 2020 - Dec 2020 · 11 mos,Delta Motors,Web Developer,Jul 2019 - Sep 2019 · 3 mos,Python,HTML,MySQL,CSS,Laravel,"Tunis, Tunisie","Tunis, Tunisie"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,https://www.linkedin.com/in/meriem-gafsi-sghaier/,Business Intelligence Developer bei Projektfab...,Région de Stuttgart,Meriem Gafsi Sghaier,Projektfabrik Weilheim GmbH,Business Intelligence Developer,juin 2021 - aujourd’hui · 9 mois,Orange Tunisie,Data Analyst Intern,févr. 2021 - mars 2021 · 2 mois,Leadership,Software Development,Microsoft Power BI,Analyse de données,Entrepôt de données,"Weilheim an der Teck, Bade-Wurtemberg, Allemagne","unis, Tunisia"
993,https://www.linkedin.com/in/omarmansr/,Business Intelligence Developer,"Berlin, Berlin, Allemagne",Omar Mansour,koawach,Business Intelligence Developer,nov. 2017 - aujourd’hui · 4 ans 4 mois,koawach,Business Intelligence Intern,avr. 2017 - nov. 2017 · 8 mois,Data Mining,SharePoint,Analyses Big Data,ASP.NET,SSIS,"Tunis, Tunisia","unis, Tunisia"
994,https://www.linkedin.com/in/malek-bejaoui/,Lead Consultant | Java Engineer | Software Arc...,"Düsseldorf, Rhénanie du Nord-Westphalie, Allem...",Malek Bejaoui,CGI,Lead Consultant,sept. 2020 - aujourd’hui · 1 an 6 mois,rising systems,DevOps Engineer,nov. 2019 - sept. 2020 · 11 mois,Java,Amazon Web Services (AWS),SQL,Web Design,Graphic Design,"Düsseldorf, North Rhine-Westphalia, Germany","unis, Tunisia"
995,https://www.linkedin.com/in/ahmeddrira/,Senior Software Engineer (VR/AR/XR) at ZREALIT...,"Mannheim, Bade-Wurtemberg, Allemagne",Ahmed Drira,ZREALITY GmbH,Senior Software Engineer,déc. 2018 - aujourd’hui · 3 ans 3 mois,ZREALITY GmbH,Software Engineer,avr. 2017 - aujourd’hui · 4 ans 11 mois,Java,C#,Android Development,iOS Development,Android,"Kaiserslautern, Rhineland-Palatinate, Germany","Kaiserslautern, Germany"
996,https://www.linkedin.com/in/ahmed-khalil-bejao...,Senior Software Engineer at Finway GmbH,"Munich, Bavière, Allemagne",Ahmed Khalil Bejaoui,finway,Senior Full Stack Engineer,mars 2020 - aujourd’hui · 2 ans,Holiday Extras GmbH,Software Engineer,nov. 2019 - mars 2020 · 5 mois,SQL,HTML,Web Development,Business Analysis,Program Management,"Munich, Bavaria, Germany","Munich Area, Germany"

In [78]:
dataframe.isnull().sum()

linkedinProfile    0
Description        0
location           0
fullName           0
company            0
jobTitle           0
jobDuration        0
company2           0
jobTitle2          0
jobDuration2       0
skill1             0
skill2             0
skill3             0
skill4             0
skill5             0
jobLocation        0
jobLocation2       0
dtype: int64

# Job duration

In [79]:
dataframe['jdt']=dataframe['jobDuration'].str.split('· ')
dataframe['jd']=dataframe['jobDuration'].str.split('· ')
dataframe['jdt2']=dataframe['jobDuration2'].str.split('· ')
dataframe['jd2']=dataframe['jobDuration2'].str.split('· ')

In [80]:
for i in range(0,len(dataframe)):

    lis=''.join(dataframe['jdt'].iloc[i].pop(1))
    s = [int(s) for s in str.split(lis) if s.isdigit()]
    if len(s) == 2:
        dataframe['jd'].iloc[i] =s[0]*12+s[1]
    elif len(s)==1:
        dataframe['jd'].iloc[i] =s[0]

In [81]:
for i in range(0,len(dataframe)):

    lis=''.join(dataframe['jdt2'].iloc[i].pop(1))
    s = [int(s) for s in str.split(lis) if s.isdigit()]
    if len(s) == 2:
        dataframe['jd2'].iloc[i] =s[0]*12+s[1]
    elif len(s)==1:
        dataframe['jd2'].iloc[i] =s[0]

In [82]:
dataframe

,linkedinProfile,Description,location,fullName,company,jobTitle,jobDuration,company2,jobTitle2,jobDuration2,...,skill2,skill3,skill4,skill5,jobLocation,jobLocation2,jdt,jd,jdt2,jd2
0,https://www.linkedin.com/in/mondher-menaa-5934...,Full-Stack developer,"Tunis, Tunisia",Mondher Menaa,NearTeam,Full-stack Developer,Jan 2020 - Present · 2 yrs 3 mos,Talan Tunisie,Software Engineer,Aug 2019 - Sep 2019 · 2 mos,...,Angular,Scrum,J2EE,.NET,"Tunis, Tunisie","Tunis, Tunisia",[Jan 2020 - Present ],27,[Aug 2019 - Sep 2019 ],2
1,https://www.linkedin.com/in/dorra-dalhoumi/?or...,"Data Analyst, BI Consultant",France,Dorra Dalhoumi,Streamlink,Business Intelligence Consultant,Jan 2022 - Present · 3 mos,Groupe Magasin Général,Ingénieur BI,Jan 2021 - Jan 2022 · 1 yr 1 mo,...,Big Data,Scrum,BI,GIT,France,"Tunis, Tunisie",[Jan 2022 - Present ],3,[Jan 2021 - Jan 2022 ],13
2,https://www.linkedin.com/in/abdouli-adem-47569...,Data Engineering Intern at Fusionbase,Germany,Abdouli Adem,Fusionbase,Data Engineering Intern,Oct 2020 - Present · 1 yr 6 mos,MS Solutions,Junior Data analyst,Jul 2019 - Aug 2019 · 2 mos,...,Java,Javascript,Python,C,Germany,"Tunis, Tunisie",[Oct 2020 - Present ],18,[Jul 2019 - Aug 2019 ],2
3,https://www.linkedin.com/in/chahnez-kasraoui-0...,Consultant BI,"Tunis, Tunisia",Chahnez KASRAOUI,EY,Consultant BI,Jul 2021 - Present · 9 mos,VERMEG,Stage PFE,Feb 2020 - Oct 2020 · 9 mos,...,Microsoft SQL Server,c++,\nHTML,Microsoft Office,"Tunis, Tunisie","Tunis, Tunisie",[Jul 2021 - Present ],9,[Feb 2020 - Oct 2020 ],9
4,https://www.linkedin.com/in/alaedine-omri/?ori...,Software engineer,"Tunis, Tunisia",Alaedine Omri,Epilert,Web Developer,Feb 2020 - Dec 2020 · 11 mos,Delta Motors,Web Developer,Jul 2019 - Sep 2019 · 3 mos,...,HTML,MySQL,CSS,Laravel,"Tunis, Tunisie","Tunis, Tunisie",[Feb 2020 - Dec 2020 ],11,[Jul 2019 - Sep 2019 ],3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,https://www.linkedin.com/in/meriem-gafsi-sghaier/,Business Intelligence Developer bei Projektfab...,Région de Stuttgart,Meriem Gafsi Sghaier,Projektfabrik Weilheim GmbH,Business Intelligence Developer,juin 2021 - aujourd’hui · 9 mois,Orange Tunisie,Data Analyst Intern,févr. 2021 - mars 2021 · 2 mois,...,Software Development,Microsoft Power BI,Analyse de données,Entrepôt de données,"Weilheim an der Teck, Bade-Wurtemberg, Allemagne","unis, Tunisia",[juin 2021 - aujourd’hui ],9,[févr. 2021 - mars 2021 ],2
993,https://www.linkedin.com/in/omarmansr/,Business Intelligence Developer,"Berlin, Berlin, Allemagne",Omar Mansour,koawach,Business Intelligence Developer,nov. 2017 - aujourd’hui · 4 ans 4 mois,koawach,Business Intelligence Intern,avr. 2017 - nov. 2017 · 8 mois,...,SharePoint,Analyses Big Data,ASP.NET,SSIS,"Tunis, Tunisia","unis, Tunisia",[nov. 2017 - aujourd’hui ],52,[avr. 2017 - nov. 2017 ],8
994,https://www.linkedin.com/in/malek-bejaoui/,Lead Consultant | Java Engineer | Software Arc...,"Düsseldorf, Rhénanie du Nord-Westphalie, Allem...",Malek Bejaoui,CGI,Lead Consultant,sept. 2020 - aujourd’hui · 1 an 6 mois,rising systems,DevOps Engineer,nov. 2019 - sept. 2020 · 11 mois,...,Amazon Web Services (AWS),SQL,Web Design,Graphic Design,"Düsseldorf, North Rhine-Westphalia, Germany","unis, Tunisia",[sept. 2020 - aujourd’hui ],18,[nov. 2019 - sept. 2020 ],11
995,https://www.linkedin.com/in/ahmeddrira/,Senior Software Engineer (VR/AR/XR) at ZREALIT...,"Mannheim, Bade-Wurtemberg, Allemagne",Ahmed Drira,ZREALITY GmbH,Senior Software Engineer,déc. 2018 - aujourd’hui · 3 ans 3 mois,ZREALITY GmbH,Software Engineer,avr. 2017 - aujourd’hui · 4 ans 11 mois,...,C#,Android Development,iOS Development,Android,"Kaiserslautern, Rhineland-Palatinate, Germany","Kaiserslautern, Germany",[déc. 2018 - aujourd’hui ],39,[avr. 2017 - aujourd’hui ],59
996,https://www.linkedin.com/in/ahmed-khalil-bejao...,Senior Software Engineer at Finway GmbH,"Munich, Bavière, Allemagne",Ahmed Khalil Bejaoui,finway,Senior Full Stack Engineer,mars 2020 - aujourd’hui · 2 ans,Holiday Extras GmbH,Software Engineer,nov. 2019 - mars 2020 · 5 mois,...,HTML,Web Development,Business Analysis,Program Management,"Munich, Bavaria, Germany","Munich Area, Germany",[mars 2020 - aujourd’hui ],2,[nov. 2019 - mars 2020 ],5

In [83]:
dataframe.drop("jobDuration", axis=1, inplace=True)
dataframe.drop("jobDuration2", axis=1, inplace=True)
dataframe.drop("jdt", axis=1, inplace=True)
dataframe.drop("jdt2", axis=1, inplace=True)

In [84]:
dataframe

,linkedinProfile,Description,location,fullName,company,jobTitle,company2,jobTitle2,skill1,skill2,skill3,skill4,skill5,jobLocation,jobLocation2,jd,jd2
0,https://www.linkedin.com/in/mondher-menaa-5934...,Full-Stack developer,"Tunis, Tunisia",Mondher Menaa,NearTeam,Full-stack Developer,Talan Tunisie,Software Engineer,Java,Angular,Scrum,J2EE,.NET,"Tunis, Tunisie","Tunis, Tunisia",27,2
1,https://www.linkedin.com/in/dorra-dalhoumi/?or...,"Data Analyst, BI Consultant",France,Dorra Dalhoumi,Streamlink,Business Intelligence Consultant,Groupe Magasin Général,Ingénieur BI,Power BI,Big Data,Scrum,BI,GIT,France,"Tunis, Tunisie",3,13
2,https://www.linkedin.com/in/abdouli-adem-47569...,Data Engineering Intern at Fusionbase,Germany,Abdouli Adem,Fusionbase,Data Engineering Intern,MS Solutions,Junior Data analyst,SQL,Java,Javascript,Python,C,Germany,"Tunis, Tunisie",18,2
3,https://www.linkedin.com/in/chahnez-kasraoui-0...,Consultant BI,"Tunis, Tunisia",Chahnez KASRAOUI,EY,Consultant BI,VERMEG,Stage PFE,analyses des données,Microsoft SQL Server,c++,\nHTML,Microsoft Office,"Tunis, Tunisie","Tunis, Tunisie",9,9
4,https://www.linkedin.com/in/alaedine-omri/?ori...,Software engineer,"Tunis, Tunisia",Alaedine Omri,Epilert,Web Developer,Delta Motors,Web Developer,Python,HTML,MySQL,CSS,Laravel,"Tunis, Tunisie","Tunis, Tunisie",11,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,https://www.linkedin.com/in/meriem-gafsi-sghaier/,Business Intelligence Developer bei Projektfab...,Région de Stuttgart,Meriem Gafsi Sghaier,Projektfabrik Weilheim GmbH,Business Intelligence Developer,Orange Tunisie,Data Analyst Intern,Leadership,Software Development,Microsoft Power BI,Analyse de données,Entrepôt de données,"Weilheim an der Teck, Bade-Wurtemberg, Allemagne","unis, Tunisia",9,2
993,https://www.linkedin.com/in/omarmansr/,Business Intelligence Developer,"Berlin, Berlin, Allemagne",Omar Mansour,koawach,Business Intelligence Developer,koawach,Business Intelligence Intern,Data Mining,SharePoint,Analyses Big Data,ASP.NET,SSIS,"Tunis, Tunisia","unis, Tunisia",52,8
994,https://www.linkedin.com/in/malek-bejaoui/,Lead Consultant | Java Engineer | Software Arc...,"Düsseldorf, Rhénanie du Nord-Westphalie, Allem...",Malek Bejaoui,CGI,Lead Consultant,rising systems,DevOps Engineer,Java,Amazon Web Services (AWS),SQL,Web Design,Graphic Design,"Düsseldorf, North Rhine-Westphalia, Germany","unis, Tunisia",18,11
995,https://www.linkedin.com/in/ahmeddrira/,Senior Software Engineer (VR/AR/XR) at ZREALIT...,"Mannheim, Bade-Wurtemberg, Allemagne",Ahmed Drira,ZREALITY GmbH,Senior Software Engineer,ZREALITY GmbH,Software Engineer,Java,C#,Android Development,iOS Development,Android,"Kaiserslautern, Rhineland-Palatinate, Germany","Kaiserslautern, Germany",39,59
996,https://www.linkedin.com/in/ahmed-khalil-bejao...,Senior Software Engineer at Finway GmbH,"Munich, Bavière, Allemagne",Ahmed Khalil Bejaoui,finway,Senior Full Stack Engineer,Holiday Extras GmbH,Software Engineer,SQL,HTML,Web Development,Business Analysis,Program Management,"Munich, Bavaria, Germany","Munich Area, Germany",2,5

In [85]:
dataframe.rename(columns={'jd': 'jobDuration1', 'jd2': 'jobDuration2','jobTitle':'jobTitle1'},inplace=True)

In [86]:
dataframe.drop(['linkedinProfile','fullName'], axis=1, inplace=True)

# Location

In [87]:
def getCountry(location) :
    country = []
    
    for x in location : 
        try :
            words = x.split()
            x = words[-1]
        except :
            x =None
        country.append(x)
    return country

In [88]:
location = dataframe['location']
country = getCountry(location)
Location = pd.DataFrame(country,columns = ['Location'])
Location

      Location
0      Tunisia
1       France
2      Germany
3      Tunisia
4      Tunisia
..         ...
956  Stuttgart
957  Allemagne
958  Allemagne
959  Allemagne
960  Allemagne

[961 rows x 1 columns]

In [89]:
jobLocation1 = getCountry(dataframe['jobLocation'])
jobLocation1 = pd.DataFrame(jobLocation1,columns = ['jobLocation1'])
jobLocation1

    jobLocation1
0        Tunisie
1         France
2        Germany
3        Tunisie
4        Tunisie
..           ...
956    Allemagne
957      Tunisia
958      Germany
959      Germany
960      Germany

[961 rows x 1 columns]

In [90]:
jobLocation2 = getCountry(dataframe['jobLocation2'])
jobLocation2 = pd.DataFrame(jobLocation2,columns = ['jobLocation2'])
jobLocation2

    jobLocation2
0        Tunisia
1        Tunisie
2        Tunisie
3        Tunisie
4        Tunisie
..           ...
956      Tunisia
957      Tunisia
958      Tunisia
959      Germany
960      Germany

[961 rows x 1 columns]

# Company

In [91]:
list_of_jobDuration1 = dataframe['jobDuration1'].tolist()
list_of_jobDuration2 = dataframe['jobDuration2'].tolist()

In [92]:
jdr2=[]
for a in list_of_jobDuration2 : 
    if isinstance(a,int) :
        jdr2.append(a)
    else :
        jdr2.append(None)

In [93]:
jobDuration2 = pd.DataFrame (jdr2, columns = ['jobDuration2'])

In [94]:
dataframe.drop(['jobDuration2'], axis=1, inplace=True)

In [95]:
dataframe = pd.concat([dataframe,jobDuration2], axis=1, join='inner')

In [96]:
dataframe

,Description,location,company,jobTitle1,company2,jobTitle2,skill1,skill2,skill3,skill4,skill5,jobLocation,jobLocation2,jobDuration1,jobDuration2
0,Full-Stack developer,"Tunis, Tunisia",NearTeam,Full-stack Developer,Talan Tunisie,Software Engineer,Java,Angular,Scrum,J2EE,.NET,"Tunis, Tunisie","Tunis, Tunisia",27,2.0
1,"Data Analyst, BI Consultant",France,Streamlink,Business Intelligence Consultant,Groupe Magasin Général,Ingénieur BI,Power BI,Big Data,Scrum,BI,GIT,France,"Tunis, Tunisie",3,13.0
2,Data Engineering Intern at Fusionbase,Germany,Fusionbase,Data Engineering Intern,MS Solutions,Junior Data analyst,SQL,Java,Javascript,Python,C,Germany,"Tunis, Tunisie",18,2.0
3,Consultant BI,"Tunis, Tunisia",EY,Consultant BI,VERMEG,Stage PFE,analyses des données,Microsoft SQL Server,c++,\nHTML,Microsoft Office,"Tunis, Tunisie","Tunis, Tunisie",9,9.0
4,Software engineer,"Tunis, Tunisia",Epilert,Web Developer,Delta Motors,Web Developer,Python,HTML,MySQL,CSS,Laravel,"Tunis, Tunisie","Tunis, Tunisie",11,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,Développeur Junior FullStack,"Schmalkalden, Thuringe, Allemagne",ROKIN,Développeur Web,ESPRIT (Ecole Supérieure Privée d'Ingénierie e...,"Développeur Android , IOS et Web",Développement iOS,Swift,Développement pour Android,Test unitaire,Scrum,"Munich, Bavière, Allemagne","unis, Tunisia",6,2.0
957,System Administrator intern at futalis GmbH,Leipzig et périphérie,futalis GmbH,System Administrator intern,Trust Medis,Engineer Internship,Linux,SQL,Java,XML,Cloud Computing,"Leipzig Area, Germany","unis, Tunisia",25,8.0
958,iOS Team Leader at fileee GmbH,"Münster, Rhénanie du Nord-Westphalie, Allemagne",fileee,iOS Team Leader,fileee,Android Developer,iOS Development,Swift (Programming Language),Objective-C,Android Development,Scrum,"Tunis, Tunisia","Münster, North Rhine-Westphalia",41,11.0
959,Software Development Engineer chez INFARM,"Berlin, Berlin, Allemagne",INFARM,Software Development Engineer,Scorable,Senior Software Engineering,Java,JavaScript,Finance,Gestion de projet,Informatique décisionnelle,"Berlin, Allemagne","Région de Berlin, Allemagne",9,59.0
960,Engineering Student at Hochschule Schmalkalden,"Schmalkalden, Thuringe, Allemagne",SEGULA Technologies,Mechanical Designer,Petrole Servie Industriel ( PSI ),Mechanical Designer,Conception assistée par ordinateur (CAD),SOLIDWORKS,Altium Designer,Solid Edge,Travail d’équipe,"Tunis, Tunisia","unis, Tunisia",3,5.0

In [97]:
dataframe.isnull().sum()

Description     0
location        0
company         0
jobTitle1       0
company2        0
jobTitle2       0
skill1          0
skill2          0
skill3          0
skill4          0
skill5          0
jobLocation     0
jobLocation2    0
jobDuration1    0
jobDuration2    4
dtype: int64

In [98]:
dataframe.dropna(inplace=True)

In [99]:
list_of_company1 = dataframe['company'].tolist()
list_of_company2 = dataframe['company2'].tolist()
jobDuration1_array = dataframe.loc[:,'jobDuration1'].values
jobDuration2_array = dataframe.loc[:,'jobDuration2'].values
jobDuration_compare = jobDuration1_array > jobDuration2_array

In [100]:
Company = []
list_of_company1 = dataframe['company'].tolist()
list_of_company2 = dataframe['company2'].tolist()
for i in range(len(dataframe)) :
    if jobDuration_compare[i] == True :
        Company.append(list_of_company1[i])
    else :
        Company.append(list_of_company2[i])

In [101]:
Company = pd.DataFrame (Company, columns = ['Company'])
Company

                               Company
0                             NearTeam
1               Groupe Magasin Général
2                           Fusionbase
3                               VERMEG
4                              Epilert
..                                 ...
919                              ROKIN
920                       futalis GmbH
921                             fileee
922                           Scorable
923  Petrole Servie Industriel ( PSI )

[924 rows x 1 columns]

In [102]:
#import openpyx as xls
excel_file=pd.ExcelWriter("company.xlsx")
Company.to_excel(excel_file)
excel_file.save()

In [32]:
company_array = Company.iloc[:,:].values

In [33]:
company_array

array([['NearTeam'],
       ['Groupe Magasin Général'],
       ['Fusionbase'],
       ['VERMEG'],
       ['Epilert'],
       ['EY'],
       ['RFC'],
       ['AGENA3000'],
       ['Start Development'],
       ['Value'],
       ['Orange'],
       ['Léni'],
       ['Electrolux'],
       ['vystem.io'],
       ['CED '],
       ['Watts'],
       ['EDF'],
       ['FIS'],
       ['CEREALIS'],
       ['ATHENA'],
       ['Bertsch'],
       ['WAPPDEV'],
       ['EY'],
       ['European Commission'],
       ['Arabesque'],
       ['Sagemcom'],
       ['Value'],
       ['YUV TV'],
       ['Mitakus analytics'],
       ['ORNESS'],
       ['Assurances COMAR'],
       ['Jurass Expertise'],
       ['Value'],
       ['Poulina Group'],
       ['IT Schrake'],
       ['Faurecia'],
       ['INNOVUP'],
       ['Université du Québec du Montréal'],
       ['Harvest Group'],
       ['INEAT Canada'],
       ['Upwork'],
       ['Lions Club Tanit Soukra'],
       ['Université du Québec à Rimouski'],
       ['ROBERT TRANSPORT'],
       ['360Medlink Inc'],
       ['Deloitte'],
       ['ESPRO Junior Entreprise'],
       ['MTF embamet'],
       ['CAE'],
       ['Vosker'],
       ['Travaris'],
       ['Bonduelle'],
       ['Unity Technologies'],
       ['ITIZEN'],
       ['SFM Technology'],
       ['UQTR - Université du Québec à Trois-Rivières'],
       ['Summit Tech'],
       ['chimicouleurs emballages métalliques'],
       ['BNP Paribas Securities Services'],
       ['CGI'],
       ['Nuvoola'],
       ['UQTR - Université du Québec à Trois-Rivières'],
       ['Revenu Québec'],
       ['Autorité  régionale de transport métropolitain'],
       ['ANPE'],
       ['GTI, Attijari Bank Group'],
       ['LGS - Une société IBM'],
       ['SER'],
       ['Bontaz Centre Equipementier Automobile'],
       ['360Medlink Inc'],
       ['Ministère de la Sécurité publique du Québec'],
       ['Oldcastle BuildingEnvelope'],
       ['Albert Davidson industries'],
       ['Solutions Techso'],
       ['Croix Bleue du Québec'],
       ['COFICAB Group'],
       ['MD Financial Management | Gestion financière MD'],
       ['IGA'],
       ['LGS - An IBM Company'],
       ['Klanik'],
       ['AMA GROUP'],
       ['KIWI Technologies Inc.'],
       ['Centre universitaire de santé McGill et IR-CUSM | McGill University Health Centre and RI-MUHC'],
       ['Sidekick Interactive'],
       ['Tremcar'],
       ['Sofrecom Tunisie'],
       ['Progi'],
       ['Value'],
       ['iA Groupe financier (Industrielle Alliance)'],
       ['Airudi Inc.'],
       ['eyful'],
       ['Gfi Informatique'],
       ['Hydro-Québec'],
       ['Levio'],
       ['Mécanique Industrielle Fortier et Fils (MIFF)'],
       ['Québecor'],
       ['Les Productions Horticoles Demers inc.'],
       ['GFT Group'],
       ['O2 Web'],
       ['Desjardins'],
       ['CAE Inc.'],
       ['Plad Equipment Ltd'],
       ['Cofomo'],
       ['PLUG & TEL'],
       ['TrackTik'],
       ["Iset'com & Sup'Com"],
       ['Touchdown Apps'],
       ['House of Commons of Canada Chambre des communes du Canada'],
       ['Procom Québec'],
       ['APPTINEO'],
       ['Freelance | Self Employed'],
       ['Trans Mountain'],
       ['Sky Engineering Industries'],
       ['Orel Services, IT Recruitment Expert'],
       ['FX Innovation'],
       ['Jemmsau'],
       ['MiLuna'],
       ['Université de Montréal'],
       ['STES Piscine'],
       ['Focus & Focus International'],
       ['360Medlink Inc'],
       ['ESPRIT'],
       ['Ciao - Services-conseils en TI'],
       ['IQware Inc.'],
       ['McGill University'],
       ["bureau d'études stambouli"],
       ['Levio'],
       ['Afrique Travaux S.a.r.l.'],
       ['École de technologie supérieure'],
       ['Highway Innovation'],
       ['Université de Moncton'],
       ['National Bank of Canada'],
       ['Fujitsu America'],
       ['Randstad Canada'],
       ['Effenti inc'],
       ['CGI'],
       ['Wood'],
       ['Banque Nationale du Canada'],
       ["P'tit chef"],
       ['Thales'],
       ['Sidekick Interactive'],
       ['Prosomo Inc.'],
       ['Techso'],
       ['BNP Paribas'],
       ['Desjardins'],
       ['DRAKKAR Digital'],
       ['Discount Car & Truck Rentals'],
       ['IMDS Canada Inc'],
       ['CGI'],
       ['Larochelle Groupe Conseil'],
       ['oXya, A Hitachi Group Company'],
       ['LGS, une société IBM'],
       ['Systematix'],
       ["Bureau d'étude Issam eddinensiri"],
       ['CETA Ingénierie'],
       ['TMX Group'],
       ['Zendesk'],
       ['Quebecor'],
       ['Sagemcom'],
       ['mthree'],
       ['NGO(Tunisian Union of Social Solidarity)'],
       ['Bell Media'],
       ['Larochelle Groupe Conseil'],
       ['Revenu Québec'],
       ['Carthago Poly Service'],
       ['Logient'],
       ['SMART Tunisie'],
       ['LGS, an IBM Company'],
       ['Nord Electro Technique'],
       ['Onetech business solutions OTBS'],
       ['Technologies IntelliCloud'],
       ['Sanofi'],
       ['GE Current, a Daintree company'],
       ['Collège La Cité'],
       ['CBC/Radio-Canada'],
       ['John Juan Burrito'],
       ['Strata Health Canada'],
       ['TD Insurance'],
       ['BMM Testlabs'],
       ['BMM Testlabs'],
       ['Bell'],
       ['IPEX Group of Companies'],
       ['WIE IEEE SPIT'],
       ['Laevitas'],
       ['Monetique Tunisie'],
       ["ESPRIT (Ecole Supérieure Privée d'Ingénierie et de Technologies)"],
       ['Futura Esprit : Club des Ingénieurs Entrepreneurs'],
       ['Wattnow'],
       ['Quantylix'],
       ['Smart Tunisian Technoparks'],
       ['Talan Tunisie'],
       ['Be Wireless Solutions'],
       ['Avaxia Consulting'],
       ['3S Standard Sharing Software'],
       ['Spark IT'],
       ['WEVIOO'],
       ['Systèmes Informatiques Tunisie'],
       ['COFICAB Group'],
       ['NEURODATA'],
       ['WEVIOO'],
       ['Clediss s.a.r.l'],
       ['IZIKOT'],
       ['B.N.S Engineering'],
       ['ELYADATA'],
       ['Cytekia'],
       ['Eurofins'],
       ['Sagemcom'],
       ['Go My Code'],
       ['Tunisie Télécom'],
       ["ESPRIT (Ecole Supérieure Privée d'Ingénierie et de Technologies)"],
       ['Institut Supérieur des Etudes Technologiques en Communications de Tunis'],
       ['Open Startup'],
       ['Industry X.0, iX.0'],
       ['Keyrus'],
       ['attijari bank'],
       ['Goldstar'],
       ['Foodwize'],
       ['Ooredoo Tunisie'],
       ['ALTRACALL'],
       ['Freelance'],
       ['Save Your Wardrobe'],
       ['AYMAX'],
       ['Sagemcom'],
       ['ThinkOcean'],
       ['Linedata'],
       ['SESAMm'],
       ['Ooredoo Tunisie'],
       ['Mezzo Relation Client'],
       ['MINOTORE'],
       ['Hult Prize Foundation'],
       ['Orange'],
       ['Agence des Monts'],
       ['armatis-lc'],
       ['DREAM TEK CONSULTING'],
       ["societe des ciments D'Enfidha SCE Tunisie"],
       ['Indépendant'],
       ['MENAPS'],
       ['Clediss s.a.r.l'],
       ['MENAPS'],
       ['Banque de Tunisie et des Émirats'],
       ['Infor'],
       ['BIAT'],
       ['Sastra Solar Energy'],
       ['Value'],
       ['Groupe SFM'],
       ["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       ['Decathlon Tunisie'],
       ['Attijari bank Tunisie'],
       ['Infor'],
       ["compagnie tunisienne d'électronique '' el athir ''"],
       ['Go My Code'],
       ['ODDO BHF'],
       ['axefinance'],
       ['SOGESTMATIC'],
       ['Banque Nationale Agricole'],
       ['Tunisie Télécom'],
       ['TECOS'],
       ['GreenFlex'],
       ['TEAMWILL CONSULTING'],
       ['CGI'],
       ['Adlere'],
       ['Enedis'],
       ['QUALIPRO'],
       ['EXAKIS NELITE'],
       ['D-one Consulting'],
       ['Veepee'],
       ['Realite digitale'],
       ['Accretio'],
       ['Tunisie Leasing & Factoring'],
       ['IT SERV'],
       ['Vizzia'],
       ['GeWinner'],
       ['Slashup Studio'],
       ['EGCI GROUP'],
       ['Vneuron'],
       ['Poulina Group Holding'],
       ['Upwork'],
       ['FIS'],
       ['TEAMWILL'],
       ["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       ['S.M.I.C. Services Marketing Informatique et Communication'],
       ["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       ['Go My Code'],
       ['Banque Zitouna'],
       ['Fraunhofer-Zentrum für Internationales Management und Wissensökonomie IMW'],
       ['Firstak'],
       ['Accretio'],
       ['44 screens'],
       ['One Gate Africa'],
       ['Smart Machines Animation'],
       ['Wimbee'],
       ['Euro-Information'],
       ['Talan'],
       ['IDLINK'],
       ['computer technologies'],
       ['Sideralba S.p.A.'],
       ['Accretio'],
       ['MEDIANET'],
       ['TurnBurn'],
       ['Featway'],
       ['HLi Tunisie'],
       ['Smart Technology'],
       ['ODDO BHF'],
       ['ADM'],
       ['TERRAKODO'],
       ['Go My Code'],
       ['Groupe PSA'],
       ['Yellowsys'],
       ['Go My Code'],
       ['VERMEG for Banking & Insurance Software'],
       ['axefinance'],
       ['Deloitte'],
       ['Freelance'],
       ['Fulfillment Bridge'],
       ['EBRD'],
       ['INNOSCAPE - Open Your Market Intelligence'],
       ['KooL Delivery'],
       ['Numeryx Tunisie'],
       ['VERMEG for Banking & Insurance Software'],
       ['SlashUp Studio'],
       ["Centre d'Etude et de Recherche des Télécommunications"],
       ['ESB Junior-Entreprise'],
       ['EcoVadis'],
       ['UBCI'],
       ['MarketBey'],
       ['DITRIOT Consulting'],
       ['EY'],
       ['plasteel tunisie'],
       ['C2E - Solutions for Cabling'],
       ['Save Your Wardrobe'],
       ['Yuvo'],
       ['Amaris Consulting'],
       ['AMZ Software'],
       ['株式会社レボーン REVORN Co., Ltd.'],
       ['SIMOP'],
       ['Ben Jemaa Motors (BMW)'],
       ['Mazars'],
       ['Elliptical Tunisie'],
       ['Amaris'],
       ['LNS CORP'],
       ['EY'],
       ['Clediss s.a.r.l'],
       ['SETTING'],
       ['IO Consulting'],
       ['TEAMWILL CONSULTING'],
       ['Drag & Code Tunisia'],
       ['Smart  Conseil'],
       ['VERMEG for Banking & Insurance Software'],
       ['KPMG'],
       ['VERMEG for Banking & Insurance Software'],
       ['Yuvo'],
       ['Sagemcom'],
       ['AZ Projet'],
       ['VERMEG for Banking & Insurance Software'],
       ['Gérance Informatique'],
       ['Tritux Group'],
       ["Société Tunisienne de l'Electricité et du Gaz (STEG)"],
       ['STAR ASSURANCES'],
       ['Lions Clubs International'],
       ['Liberrex'],
       ['ESPRO Junior Entreprise'],
       ['ShopiApps OÜ'],
       ['SCIN'],
       ["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       ['Sagemcom'],
       ['The maze group'],
       ['iObeya'],
       ['2i com'],
       ['Valtech informatique'],
       ['Linkia'],
       ['RFC'],
       ['Discovery Informatique SA'],
       ['SHEMS FM'],
       ['TUNISAIR'],
       ['Avo Carbon France   (Société de Câblage Electrique et Electromécanique Tunisie)'],
       ['Icar industrie de carrossage'],
       ['NeoXam'],
       ['Kaoun - كَوْن'],
       ['Sopra HR Software'],
       ['La Poste Tunisienne'],
       ['Apave'],
       ["ESPRIT (Ecole Supérieure Privée d'Ingénierie et de Technologies)"],
       ['Elektron Technology'],
       ['Zitouna Bank'],
       ['BBC SARL'],
       ['Sofrecom Tunisie'],
       ['shopreme - Scan & Go'],
       ['axefinance'],
       ['Attijari bank Tunisie'],
       ['VERMEG for Banking & Insurance Software'],
       ['SQOIN'],
       ['BIATLABS'],
       ['IT GATE Group'],
       ['NTECH Consulting'],
       ['FININFO SOLUTIONS'],
       ['CSI'],
       ['CDCP Digital Learning'],
       ['ACTIA Engineering Services'],
       ['MaibornWolff GmbH'],
       ['Groupe NGI International'],
       ['DATAHORIZON'],
       ['Centre Supérieur de Formation (CSF)'],
       ['IBL ELECTRONICS'],
       ['Sofrecom Tunisie'],
       ['Sofrecom Tunisie'],
       ['Direction Générale des Douanes'],
       ['Sagemcom'],
       ['Sofrecom Tunisie'],
       ['IENA | Performance Management et Finance Consulting'],
       ['Réalité Digitale'],
       ['Devoteam'],
       ['Ucase Consulting'],
       ['Klanik'],
       ['Talan'],
       ['Wide Web Words'],
       ['DefensyLab'],
       ['SIGA'],
       ['Airbus'],
       ['Crédit Agricole Consumer Finance'],
       ['Spark-it Group'],
       ['SKOTT GROUP'],
       ['GROUPAGORA'],
       ['IS CONSEIL'],
       ['Valeo'],
       ['SQUIKIT'],
       ['Syngenta'],
       ["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       ['BNP Paribas Securities Services'],
       ['Cooptalis'],
       ['DRT Technology Services, L.L.C.'],
       ["ESPRIT (Ecole Supérieure Privée d'Ingénierie et de Technologies)"],
       ['Sopra HR Software'],
       ['Actinvision'],
       ['Destination Hostels'],
       ['Convergence.link'],
       ['Esprit School of Business'],
       ['Mobile powered'],
       ['WizyVision'],
       ['Ecertic Digital Solutions'],
       ['MED Training'],
       ['LOG SYSTEM'],
       ['Dawan'],
       ['Laboratoires Adwya'],
       ['Leoxa'],
       ['STAR ASSURANCES'],
       ['Contentsquare'],
       ['Inetum'],
       ['Safran'],
       ['mistertee.fr'],
       ['Clevertech France'],
       ['Sobflous'],
       ['ITGate Group'],
       ['Umanis'],
       ['Notion Edge'],
       ['HEINEKEN France'],
       ['Sintegra Consulting'],
       ['BNP Paribas CIB'],
       ['TESTED4YOU'],
       ['Prime Analytics'],
       ['ESPRIT'],
       ['Volvo Truck Center'],
       ['Rahba.tn'],
       ['TEAMWILL CONSULTING'],
       ['Orange'],
       ['Zaion'],
       ['Actinvision'],
       ['\u200bPERITIS'],
       ['Vistaprint'],
       ['NDI'],
       ['Groupe Magasin Général / Auchan'],
       ['Sopra HR Software'],
       ['Bourse de Tunis'],
       ['Egis'],
       ['ADDINN'],
       ['InVivo'],
       ['AFD Tech'],
       ['EY'],
       ['InVivo Retail'],
       ['ACENSI NORD'],
       ['Indépendant'],
       ['VAGANET'],
       ['Agyla'],
       ['VERMEG for Insurance & Finance Software'],
       ['UIB - Groupe Société Générale'],
       ['Andex'],
       ['IM CONSEIL ET SERVICES'],
       ['La Banque Postale'],
       ['Indépendant'],
       ['BNP Paribas'],
       ['Avempace'],
       ['BEEZEN'],
       ['the Kam company'],
       ['Hermès'],
       ['Candriam'],
       ['Airbus'],
       ['Tata Consultancy Services'],
       ['ITSS'],
       ['Gan Assurances'],
       ['CGI'],
       ['Adlere'],
       ['D-one Consulting'],
       ['GreenFlex'],
       ['Enedis'],
       ['EXAKIS NELITE'],
       ['Orange Business Services'],
       ['QUALIPRO'],
       ['Capgemini Engineering'],
       ['Think-it'],
       ['Sopra HR Software'],
       ['Gan Assurances'],
       ['FINAXYS'],
       ['Orange Business Services'],
       ['Capgemini Engineering'],
       ['INGENIANCE'],
       ['Softtodo'],
       ['Synechron'],
       ['Sopra Steria'],
       ['Devoteam Management Consulting'],
       ['SoyHuCe'],
       ['NUMERYX'],
       ['Conseil National des Ordres des Pharmaciens'],
       ['Piscines Magiline'],
       ['hyperbios'],
       ['Abington Advisory'],
       ['Sopra HR Software'],
       ['Elsevier'],
       ['Autoliv'],
       ['Direct Fleet'],
       ['Banque Nationale Agricole'],
       ['VERMEG for Banking & Insurance Software'],
       ['TECOS'],
       ['GreenFlex'],
       ['Bpifrance'],
       ['Freelance'],
       ['Adlere'],
       ['Enedis'],
       ['QUALIPRO'],
       ['EXAKIS NELITE'],
       ['D-one Consulting'],
       ["ENSIM Ecole d'ingénieurs Le Mans Université"],
       ['Sofrecom'],
       ['ODDO BHF'],
       ["3iL - Ecole d'ingénieurs en informatique - Limoges / Rodez"],
       ['IEEE'],
       ['Talan Tunisie'],
       ['Sagemcom'],
       ['Freelance'],
       ['CANAL+ Group'],
       ['Assurances Maghrebia'],
       ["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       ['RHIS Software'],
       ['Go My Code'],
       ['VOUSFINANCER - Groupe ASSU 2000'],
       ['SSTM'],
       ['DocDoku'],
       ["Institut Supérieur des Mathématiques Appliquées et de l'Informatique de Kairouan (ISMAIK)"],
       ['Société Générale'],
       ['Publicis Sapient'],
       ['Solvay'],
       ['Educacode'],
       ['Mobile devices Ingenierie'],
       ['Base Développement'],
       ['MSBI'],
       ['TREND-IT'],
       ['Calizy'],
       ['Quantylix'],
       ['MIDWAY'],
       ['ST2i'],
       ['Pachira Pay'],
       ['Tech1'],
       ['Sofrecom'],
       ['Sodexo'],
       ['Alphonse'],
       ['Talan'],
       ['Almavia - filiale du Groupe Nextedia'],
       ['CGI'],
       ['COLAS'],
       ['One TECH Business Solutions'],
       ['SECHE ALLIANCE'],
       ['Bel'],
       ['Insign - Creative Partners'],
       ['IBM'],
       ['Demand Driven Technologies'],
       ['Wimbee'],
       ['Société Générale'],
       ['Agyla.Cloud'],
       ['numberly (1000mercis Group)'],
       ['FORTICAS'],
       ['Microsoft'],
       ['COORDOGEC SECURITE'],
       ['My Money Bank'],
       ['Astrolab France'],
       ['Davidson consulting'],
       ['Alight Conseil France'],
       ['Piland'],
       ['Coursera'],
       ['Datagram'],
       ['Genical'],
       ['Convergen'],
       ["ESPRIT (Ecole Supérieure Privée d'Ingénierie et de Technologies)"],
       ['Laevitas'],
       ['Business & Decision Tunisie'],
       ['Althica Data Science'],
       ["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       ['Sofrecom Tunisie'],
       ['Be Wireless Solutions'],
       ['EY'],
       ['DREAM TEK CONSULTING'],
       ['3S Standard Sharing Software'],
       ["ESPRIT (Ecole Supérieure Privée d'Ingénierie et de Technologies)"],
       ['Open Startup'],
       ['BIAT'],
       ['B.N.S Engineering'],
       ['Laevitas'],
       ['XPR'],
       ['JTS (Jellizi Technologie Services)'],
       ['satoripop'],
       ['MSDigital34'],
       ['Albuhaira Invest'],
       ['INCEPTUM Junior Entreprise'],
       ['BIAT'],
       ['AIESEC'],
       ['Tourisfair'],
       ['Groupe HLi'],
       ['PENTABELL'],
       ['Reevalo'],
       ['Quant-Dev'],
       ['Save Your Wardrobe'],
       ['EY'],
       ['Banque internationale arabe de Tunisie'],
       ['Codix'],
       ['Avaxia Consulting'],
       ['Go My Code'],
       ['ICAR Sousse'],
       ['COFICAB Group'],
       ['B Consulting'],
       ['Comité Général des Assurances -CGA-'],
       ["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       ['Manifold Ventures LLC'],
       ['STE X-PERT'],
       ['Sofrecom Tunisie'],
       ['BIAT'],
       ['Lions Clubs International'],
       ['Value'],
       ['Global Solutions Services'],
       ['armatis-lc'],
       ['KORSGY'],
       ['SPIKE-X'],
       ['ABSHORE'],
       ['The AI Institute'],
       ["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       ['Telnet'],
       ['CoachHub - The digital coaching platform'],
       ['SAWOO'],
       ['Talan'],
       ['IT Schrake'],
       ['MS Solutions (Monetics Services Solutions)'],
       ['SNIM (Société nationale industrielle et minière)'],
       ['Valeo'],
       ['VIVERE GmbH'],
       ["ESPRIT (Ecole Supérieure Privée d'Ingénierie et de Technologies)"],
       ['Mazda Motor Europe'],
       ['BABLE Smart Cities'],
       ['InstaDeep Ltd'],
       ['TGF Schmalkalden Dermbach GmbH'],
       ['Fraunhofer IPA'],
       ['ROKIN'],
       ['Trust Medis'],
       ['fileee'],
       ['INFARM'],
       ['Petrole Servie Industriel ( PSI )'],
       ['Higher institute of Engineering and Technology , ESPRIT ,Tunisia'],
       ['FERCHAU GmbH'],
       ['Sauels Schinken'],
       ['OuiCoding'],
       ['DRÄXLMAIER Group'],
       ['acardo group ag'],
       ['PubNative (Now Verve Group)'],
       ['cadooz GmbH'],
       ['Huawei Tunisie'],
       ['Cynapsys It Hotspot'],
       ['Mercury Media Technology GmbH'],
       ['T-Systems Multimedia Solutions GmbH'],
       ['iNNOVO Cloud GmbH'],
       ['SEI Swiss Engineering Institute AG'],
       ['The unbelievable Machine Company GmbH'],
       ['ODDO BHF'],

# Skills

In [34]:
def firstWord(skill) :
    list=[]
    for i in skill :
        i = i.split()[0]
        list.append(i)
    return list

In [35]:
skill1 = firstWord(dataframe['skill1'])
skill2 = firstWord(dataframe['skill2'])
skill3 = firstWord(dataframe['skill3'])
skill4 = firstWord(dataframe['skill4'])
skill5 = firstWord(dataframe['skill5'])

In [36]:
skill1 = pd.DataFrame(skill1,columns = ['skill1'])
skill2 = pd.DataFrame(skill2,columns = ['skill2'])
skill3 = pd.DataFrame(skill3,columns = ['skill3'])
skill4 = pd.DataFrame(skill4,columns = ['skill4'])
skill5 = pd.DataFrame(skill5,columns = ['skill5'])

In [37]:
skill = pd.concat([skill1, skill2,skill3,skill4,skill5], axis=1, join='inner')

In [38]:
skill

            skill1      skill2         skill3   skill4        skill5
0             Java     Angular          Scrum     J2EE          .NET
1            Power         Big          Scrum       BI           GIT
2              SQL        Java     Javascript   Python             C
3         analyses   Microsoft            c++     HTML     Microsoft
4           Python        HTML          MySQL      CSS       Laravel
..             ...         ...            ...      ...           ...
919  Développement       Swift  Développement     Test         Scrum
920          Linux         SQL           Java      XML         Cloud
921            iOS       Swift    Objective-C  Android         Scrum
922           Java  JavaScript        Finance  Gestion  Informatique
923     Conception  SOLIDWORKS         Altium    Solid       Travail

[924 rows x 5 columns]

In [39]:
dataframe = pd.concat([skill,Company], axis=1, join='inner')
dataframe

,skill1,skill2,skill3,skill4,skill5,Company
0,Java,Angular,Scrum,J2EE,.NET,NearTeam
1,Power,Big,Scrum,BI,GIT,Groupe Magasin Général
2,SQL,Java,Javascript,Python,C,Fusionbase
3,analyses,Microsoft,c++,HTML,Microsoft,VERMEG
4,Python,HTML,MySQL,CSS,Laravel,Epilert
...,...,...,...,...,...,...
919,Développement,Swift,Développement,Test,Scrum,ROKIN
920,Linux,SQL,Java,XML,Cloud,futalis GmbH
921,iOS,Swift,Objective-C,Android,Scrum,fileee
922,Java,JavaScript,Finance,Gestion,Informatique,Scorable
923,Conception,SOLIDWORKS,Altium,Solid,Travail,Petrole Servie Industriel ( PSI )

In [40]:
word_vectors = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin',binary=True)

In [41]:
def wordEmbedding(skill):
    skill_ret=[]
    
    for i in skill:
        try :
            i=word_vectors.get_vector(i)
        except :
            i=None
        skill_ret.append(i)
    return skill_ret

In [42]:
skill1_w2v = wordEmbedding(dataframe['skill1'])
skill2_w2v = wordEmbedding(dataframe['skill2'])
skill3_w2v = wordEmbedding(dataframe['skill3'])
skill4_w2v = wordEmbedding(dataframe['skill4'])
skill5_w2v = wordEmbedding(dataframe['skill5'])

In [43]:
skill1 = pd.DataFrame(list(map(np.ravel, skill1_w2v)))
skill2 = pd.DataFrame(list(map(np.ravel, skill2_w2v)))
skill3 = pd.DataFrame(list(map(np.ravel, skill3_w2v)))
skill4 = pd.DataFrame(list(map(np.ravel, skill4_w2v)))
skill5 = pd.DataFrame(list(map(np.ravel, skill5_w2v)))

In [44]:
skill1["skill1"] = skill1.sum(axis=1)
skill2["skill2"] = skill2.sum(axis=1)
skill3["skill3"] = skill3.sum(axis=1)
skill4["skill4"] = skill4.sum(axis=1)
skill5["skill5"] = skill5.sum(axis=1)

In [45]:
dataframe_final = pd.concat([skill1["skill1"],skill2["skill2"],skill3["skill3"],skill4["skill4"],skill5["skill5"],Company], axis=1, join='inner')

In [47]:
X = dataframe_final.iloc[:,0:-1].values

In [48]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters =20 , init = 'k-means++', random_state = 42)
y_kmeans = kmeans.fit_predict(X)

In [49]:
y_kmeans

array([16, 15, 19,  2, 14, 12,  5, 13, 15, 10,  4,  6, 10,  6, 17,  7, 19,
       15,  7, 10, 17, 18,  2, 18, 18, 11, 17, 19,  9,  7, 18, 14, 18,  7,
       17,  1,  3, 12,  7, 12, 12, 16,  9, 17,  4, 13,  3,  5,  2,  9,  5,
       13,  6,  1,  9, 11, 14,  0,  1, 15, 16, 13,  7, 19,  1,  3,  8,  8,
        8,  8, 14,  2,  1, 15,  8,  3,  7,  8,  8,  0, 16, 16,  7,  1,  0,
        8, 13, 10,  2, 12, 19,  7,  5, 13, 16, 17, 11, 18, 16,  5,  4,  2,
        1,  2,  1, 14, 19, 14,  8, 14, 12, 12, 13, 19, 18,  3, 16,  2,  0,
        0,  0,  9,  2,  3, 13, 17, 13,  0, 13,  7,  3, 17, 16, 12, 10,  9,
       18, 15,  4,  2, 14, 17,  5,  9,  2,  5, 19, 17, 17,  8,  3, 16, 16,
       10,  2,  2,  0, 14,  1, 19,  9,  3, 10, 11, 17, 17, 16,  4, 12, 18,
        5, 16, 19, 14, 12,  9,  7,  5,  8,  8,  6,  9, 12,  9,  3, 12, 18,
       16, 18,  5, 13,  2,  3,  7, 16, 11, 13, 18, 18,  7,  8,  7,  8, 11,
        2, 11,  8,  5, 16,  9,  3, 14, 12,  0,  2,  2, 19, 14, 11, 17,  6,
       15, 11, 13,  1,  5,  3,  2, 10, 17, 12, 16,  7, 17,  2,  3,  7,  8,
        5,  7, 13, 18, 13, 19, 15, 16,  2,  6,  0,  5, 16, 13,  1,  6, 12,
       12,  2, 14,  4,  8, 13,  4,  9,  0, 11,  1, 12, 12,  3,  8, 13, 18,
        4,  5, 15, 12,  7, 19, 13,  8, 15,  1,  6,  8,  3, 12,  0, 16, 16,
       13,  2,  0, 14,  0, 15,  3,  5,  9,  2, 16,  2, 10,  1,  7,  6,  6,
       15, 15, 10,  3, 18,  9,  4,  4,  2, 12, 13,  3,  6,  3,  8,  9, 11,
       19,  3, 10, 13,  5,  5,  7, 18, 12,  3, 12,  6,  8,  7,  1, 16, 11,
       15, 11,  0,  8, 19,  2, 17,  2, 11,  9,  1,  9, 17, 18,  5,  2,  9,
        9,  2,  5,  3, 12, 12, 18,  3,  6, 17,  5, 11,  8, 12, 14,  3, 13,
        3, 16,  1,  2,  0,  6,  3, 13, 18,  7, 17,  3, 15,  7,  9,  3,  0,
       17,  5,  6, 18,  6,  1,  3, 13, 15, 13,  9, 10, 13, 13, 14,  3,  8,
        1, 12, 12,  6,  0,  6,  4, 13, 14, 12, 13,  5, 14, 13, 10,  5,  3,
        5,  8,  3, 11,  3,  8,  0, 12, 13,  7, 11,  7,  7, 13, 18,  5,  3,
        9, 12, 16, 10,  7, 15, 17,  3, 12, 15,  0,  7, 17, 10, 19, 12, 16,
       19,  1,  3,  3, 16,  6, 10, 19,  9,  3, 13,  7, 15, 14, 18, 18,  9,
        2, 16,  5, 10, 13,  4,  5, 14, 17,  8,  1,  4, 10, 14,  9, 10,  9,
       11, 15, 19, 17, 11,  8, 13, 11, 14,  4,  0,  3,  9, 17, 17, 16, 11,
       17,  3, 17,  0, 19, 11, 16,  3,  7,  4,  4,  9,  8, 13, 18, 12, 12,
        6, 12, 12,  2, 14,  4,  8, 13,  4,  9,  0, 11, 19, 19, 18,  8,  3,
        8,  7,  3, 11, 13, 13,  5, 12,  3,  0,  5, 18,  2,  1,  7,  7, 18,
        8,  2,  3,  4,  7, 15,  3, 13, 17,  5, 15, 10,  7,  2, 13, 19,  5,
        3, 15, 13, 17, 12,  9,  4,  0,  2, 16, 19, 10,  3,  5, 11, 16,  5,
       16, 16, 11, 19, 15,  9, 12,  2,  5, 13,  2, 15, 17,  7, 12, 14,  8,
        8, 10, 17, 18, 18,  0,  2, 10,  7,  9,  8,  8, 12, 12,  7,  6,  7,
        2,  2,  3,  5, 15, 18,  8, 16,  3, 13,  9,  4, 16,  2,  7,  6,  7,
        2, 11,  9,  7, 16,  3,  2,  0,  5, 14,  1,  0,  9, 13,  9,  4, 10,
        0,  2,  3,  5,  1, 16,  0,  3,  4,  1,  5, 16,  9, 17,  0, 15,  7,
        4, 15, 19,  3, 19, 13,  5,  5,  1, 17,  6,  6,  9, 13,  0, 14,  8,
        6, 11, 11,  4, 19,  8, 12, 19, 19, 18,  8,  3,  8,  7,  3, 17, 11,
       13, 13,  5, 12,  3,  0,  5, 18,  2,  3,  1,  7,  7, 18,  8,  2,  3,
        4,  7, 15,  3, 13, 17,  5, 15, 10,  7,  2, 13, 19,  5,  3, 15, 13,
       17, 12,  9,  4,  0,  2, 16, 19,  9, 10,  3,  5, 11, 16,  7, 11,  7,
        7, 13, 18,  5,  3,  9, 12, 16, 10,  1, 12, 12,  6,  0,  6,  4, 13,
       14, 12, 13,  5, 14, 13,  5, 14, 17,  8,  1,  4, 10, 14,  9, 10,  9,
       11, 15, 19, 17, 11,  8, 13, 11, 14,  4,  0,  3,  9, 17, 17, 16, 11,
       17,  3, 17,  0, 19, 11, 16,  3,  7,  4,  4,  9,  3,  8, 13, 18, 12,
       12, 13,  7, 11,  7, 17, 17,  9,  8,  1, 11, 12, 19, 12,  7,  6,  4,
       16, 10,  1,  4, 10,  0, 17,  2,  4,  8, 16, 15,  7, 13,  1, 16, 14,
       19, 16, 16,  2,  7, 15,  9,  7,  0, 13, 11, 12,  9, 17,  2, 15,  5,
        3, 18, 16, 19,  1, 14, 14,  3,  7, 13, 10, 13,  7, 16,  4,  2,  4,
       18, 15, 15,  9,  2,  0,  5, 14,  1,  0,  9, 13,  9,  4, 10,  0,  2,
        3,  5,  1, 16,  0,  3])

In [50]:
clusters = pd.DataFrame(y_kmeans,columns=['clusters'])

In [51]:
clusters

     clusters
0          16
1          15
2          19
3           2
4          14
..        ...
919         5
920         1
921        16
922         0
923         3

[924 rows x 1 columns]

In [52]:
dataframe_final

,skill1,skill2,skill3,skill4,skill5,Company
0,-10.629898,-2.116829,-3.285862,-8.884323,-4.378754,NearTeam
1,1.531090,-6.957410,-3.285862,-5.930496,-4.594162,Groupe Magasin Général
2,-8.238510,-10.629898,-5.781689,-4.307938,-4.604481,Fusionbase
3,0.000000,-3.219833,0.000000,-5.239471,-3.219833,VERMEG
4,-4.307938,-5.239471,-6.119751,-5.454231,0.000000,Epilert
...,...,...,...,...,...,...
919,-1.338959,-3.336359,-1.338959,-0.087780,-3.285862,ROKIN
920,-4.848153,-8.238510,-10.629898,-5.598227,-2.278194,futalis GmbH
921,-9.950710,-3.336359,0.000000,-10.607506,-3.285862,fileee
922,-10.629898,-10.363647,3.979265,1.605331,3.124928,Scorable
923,1.408035,0.000000,-1.884857,-0.110161,1.188118,Petrole Servie Industriel ( PSI )

In [53]:
X_train = dataframe_final.iloc[:, :-1].values
y_train = y_kmeans

In [54]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Predicting a new result

In [55]:
skill1 , skill2 , skill3 , skill4 , skill5 = 'Java' , 'HTML' ,'SQL' , 'CSS' , 'Angular'

In [56]:
skill1=word_vectors.get_vector(skill1)
skill2=word_vectors.get_vector(skill2)
skill3=word_vectors.get_vector(skill3)
skill4=word_vectors.get_vector(skill4)
skill5=word_vectors.get_vector(skill5)

In [57]:
def SumofArray(arr):
    sum=0
    n = len(arr)
    for i in range(n):
        sum = sum + arr[i]
    return sum

In [58]:
skill1 = SumofArray(skill1)
skill2 = SumofArray(skill2)
skill3 = SumofArray(skill3)
skill4 = SumofArray(skill4)
skill5 = SumofArray(skill5)

In [59]:
cluster = int(classifier.predict([[skill1,skill2,skill3,skill4,skill5]]))

In [60]:
cluster

1

In [61]:
def findCompanies(clusters,cluster,company_array) :
    list=[]
    for i in range(len(y_kmeans)) :
        if int(y_kmeans[i]) == cluster : 
            list.append(company_array[i])
    return list

In [62]:
companies = findCompanies(y_kmeans, cluster,company_array)

In [63]:
companies

[array(['Faurecia'], dtype=object),
 array(['ITIZEN'], dtype=object),
 array(['BNP Paribas Securities Services'], dtype=object),
 array(['ANPE'], dtype=object),
 array(['Albert Davidson industries'], dtype=object),
 array(['Sidekick Interactive'], dtype=object),
 array(['Cofomo'], dtype=object),
 array(['TrackTik'], dtype=object),
 array(['Sagemcom'], dtype=object),
 array(['Linedata'], dtype=object),
 array(['axefinance'], dtype=object),
 array(['Veepee'], dtype=object),
 array(["Ecole Supérieure Privée d'Ingénierie et de Technologies - ESPRIT"],
       dtype=object),
 array(['ODDO BHF'], dtype=object),
 array(['Elliptical Tunisie'], dtype=object),
 array(['Yuvo'], dtype=object),
 array(['NeoXam'], dtype=object),
 array(['CDCP Digital Learning'], dtype=object),
 array(['IENA | Performance Management et Finance Consulting'],
       dtype=object),
 array(['Volvo Truck Center'], dtype=object),
 array(['La Banque Postale'], dtype=object),
 array(['Publicis Sapient'], dtype=object),
 array(['MS Solutions (Monetics Services Solutions)'], dtype=object),
 array(['Trust Medis'], dtype=object),
 array(['FERCHAU GmbH'], dtype=object),
 array(['tracekey solutions GmbH'], dtype=object),
 array(['Publicis Sapient'], dtype=object),
 array(['IENA | Performance Management et Finance Consulting'],
       dtype=object),
 array(['La Banque Postale'], dtype=object),
 array(['Developer Circles from Facebook'], dtype=object),
 array(['EY'], dtype=object),
 array(['SprintEins'], dtype=object),
 array(['Spark Networks'], dtype=object),
 array(['MS Solutions (Monetics Services Solutions)'], dtype=object),
 array(['futalis GmbH'], dtype=object)]

In [67]:
companies[1][0]

'ITIZEN'

In [69]:
for i in range(10):
    print(companies[i][0])

Faurecia
ITIZEN
BNP Paribas Securities Services
ANPE
Albert Davidson industries
Sidekick Interactive
Cofomo
TrackTik
Sagemcom
Linedata